spring:
  application:
    name: admin
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      ui:
        public-url: http://localhost:8000/admin

server:
  port: 80

management:
  server:
    port: 81
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    path: build/log