server:
  port: 8761
  forward-headers-strategy: native

spring:
  application:
    name: admin
  boot:
    admin:
      context-path: /monitor
  security:
    user:
      name: ${USER_NAME:admin}
      password: ${USER_PASSWORD:admin}

eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    path: ./log