spring:
  application:
    name: admin
#  security:
#    user:
#      name: admin
#      password: admin

eureka:
  client:
    service-url:
      defaultZone: ${eureka_servers:http://localhost:8761/eureka}

server:
  port: 8090

management:
  server:
    port: 8091
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    path: build/log